### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by Cr1stalz** [NekonexDev/MangaLibAPI#1]
При авторизации вылезает сообщение `data: { message: 'CSRF token mismatch.' },`. Из-за чего может быть ошибка?

p.s.: я впервые занимаюсь post-запросами

**Comment by Cr1stalz** [comment]
есть пару моментов по документации, проще поговорить в дисе `@cr1stalz`

**Comment by NekonexDev** [comment]
Если вам чем то это поможет, изпользуете здешний код: https://github.com/OnlyFart/Elib2Ebook/blob/master/Elib2Ebook/Logic/Getters/RanobeLib/MangaLibGetterBase.cs

> При авторизации вылезает сообщение `data: { message: 'CSRF token mismatch.' },`. Из-за чего может быть ошибка?
> 
> p.s.: я впервые занимаюсь post-запросами

**Comment by NekonexDev** [comment]
Думаю на вопросы я ответил, так что тред пожалуй закрою
